### PR TITLE
fix: don't accept connections initiated by browsers

### PR DESCRIPTION
**Pull request by dappelt**
See https://github.com/sharafian/moneyd/issues/2

### CODE REVIEW

**Comment by sharafian** [comment]
I'm going to test this with https://github.com:sharafian/minute , to make sure it still works. Otherwise we might have to find another way to block browser requests, because browser extensions should be able to access moneyd

**Comment by sharafian** [comment]
Yeah, looks like it gets disconnected with:

```
  ilp-plugin-mini-accounts got connection +5s
  ilp-plugin-mini-accounts Closing a websocket connection received from a browser. Origin is chrome-extension://opeoehdbenjhggjfpljiandbofihhjed +0ms
```

Could we only block origins that are from webpages?

**Comment by dappelt** [comment]
Can you try to add the URL of moneyd to the extension's mainfest. Like this https://developer.chrome.com/extensions/xhr

**Comment by sharafian** [comment]
The thing is that chrome doesn’t block the extension from making the request, but it does set an origin header on it

**Comment by dappelt** [comment]
Yes, I understand. Adding the URL under permissions should stop chrome from setting the origin header.

**Comment by dappelt** [comment]
added a whitelist to only accept connections from known extensions

**Review by sharafian — CHANGES_REQUESTED** [review]
We shouldn't hard code which extensions are allowed to use moneyd, because then it prevents people from developing extensions that use our stack. What would be the problem with allowing any chrome extension to access moneyd? I think installing a chrome extension is equivalent to installing a program in terms of trusting it to open local services

**Review by sharafian — APPROVED** [review]

**Pull request merged**
